#!/usr/bin/env python3
"""Download local video model weights from a manifest.

This script intentionally keeps real model weights out of Git history. It reads
`config/model_weights.example.json` by default and downloads selected Hugging
Face repositories into `models/` on the local machine.

Usage:
  python scripts/download_model_weights.py --list
  python scripts/download_model_weights.py --model wan_t2v_1_3b
  python scripts/download_model_weights.py --all
  HF_TOKEN=... python scripts/download_model_weights.py --model cogvideox_5b

Notes:
- Some upstream models are gated. You must accept their license on Hugging Face
  and provide HF_TOKEN when required.
- Do not commit `models/`, `.safetensors`, `.bin`, `.ckpt`, or other weight
  files. They are ignored by `.gitignore`.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "config" / "model_weights.example.json"


def load_manifest(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"manifest not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def print_models(manifest: dict[str, Any]) -> None:
    models = manifest.get("models", {})
    print("Available models:\n")
    for name, cfg in models.items():
        print(f"- {name}")
        print(f"  backend: {cfg.get('backend')}")
        print(f"  repo_id: {cfg.get('repo_id')}")
        print(f"  local_dir: {cfg.get('local_dir')}")
        print(f"  env: {cfg.get('env_path_key')}={cfg.get('local_dir')}")
        print(f"  note: {cfg.get('recommended_for', '')}\n")


def ensure_huggingface_hub():
    try:
        from huggingface_hub import snapshot_download  # type: ignore
    except Exception as exc:
        raise RuntimeError(
            "Install huggingface_hub first: pip install huggingface_hub hf_transfer"
        ) from exc
    return snapshot_download


def download_one(name: str, cfg: dict[str, Any], *, token: str | None, revision: str | None, local_files_only: bool) -> Path:
    if cfg.get("provider") != "huggingface":
        raise ValueError(f"unsupported provider for {name}: {cfg.get('provider')}")
    repo_id = cfg.get("repo_id")
    local_dir = ROOT / str(cfg.get("local_dir"))
    if not repo_id:
        raise ValueError(f"repo_id missing for {name}")
    local_dir.mkdir(parents=True, exist_ok=True)
    snapshot_download = ensure_huggingface_hub()
    print(f"Downloading {name}: {repo_id} -> {local_dir}")
    path = snapshot_download(
        repo_id=repo_id,
        local_dir=str(local_dir),
        local_dir_use_symlinks=False,
        token=token,
        revision=revision,
        local_files_only=local_files_only,
        resume_download=True,
    )
    resolved = Path(path)
    print(f"Completed: {resolved}")
    print(f"Set environment variable: {cfg.get('env_path_key')}={resolved}")
    return resolved


def write_env_fragment(downloaded: dict[str, Path], manifest: dict[str, Any], output: Path) -> None:
    lines = [
        "# Generated by scripts/download_model_weights.py",
        "# Copy these lines into .env or export them in your shell.",
    ]
    models = manifest.get("models", {})
    for name, path in downloaded.items():
        env_key = models[name].get("env_path_key")
        backend = models[name].get("backend")
        if env_key:
            lines.append(f"{env_key}={path}")
        if backend:
            lines.append(f"# VIDEO_BACKEND={backend}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote env fragment: {output}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Download local AI video model weights outside Git history.")
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST), help="Path to model manifest JSON.")
    parser.add_argument("--model", action="append", help="Model key to download. Can be repeated.")
    parser.add_argument("--all", action="store_true", help="Download all models in the manifest.")
    parser.add_argument("--list", action="store_true", help="List available models and exit.")
    parser.add_argument("--revision", default=None, help="Optional Hugging Face revision/branch/commit.")
    parser.add_argument("--local-files-only", action="store_true", help="Do not access network; validate local cache only.")
    parser.add_argument("--env-output", default=".env.models.local", help="Where to write model path env variables.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = load_manifest(Path(args.manifest))
    if args.list:
        print_models(manifest)
        return 0
    models = manifest.get("models", {})
    selected = list(models.keys()) if args.all else (args.model or [])
    if not selected:
        print("No model selected. Use --list, --model <name>, or --all.", file=sys.stderr)
        return 2
    token = os.getenv("HF_TOKEN") or os.getenv("HUGGINGFACE_HUB_TOKEN")
    downloaded: dict[str, Path] = {}
    for name in selected:
        if name not in models:
            print(f"Unknown model: {name}", file=sys.stderr)
            print_models(manifest)
            return 2
        downloaded[name] = download_one(
            name,
            models[name],
            token=token,
            revision=args.revision,
            local_files_only=args.local_files_only,
        )
    write_env_fragment(downloaded, manifest, ROOT / args.env_output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
